services:
  simulator:
    image: gastudil/demps:02.00-devs-base
    platform: linux/amd64 
    hostname: demps-devs
    container_name: simulator
    ports:
      - 8000:80
    volumes:
         - .:/home/demps-user/workspace
         #- .:/home/demps-user
    #volumes:
      #- ./planet.openstreetmap.org:/home/demps-user/planet.openstreetmap.org
      #- ./sim:/home/demps-user/sim
      #- ./conf.d:/usr/local/etc/demps/conf.d
      #- ./logs:/var/log/demps
    networks:
      - back_net
      
  oes:
    image: gastudil/oes:01.00
    platform: linux/amd64 
    hostname: oes
    container_name: oes
    command: ["python3","/home/oes/openElevationServer.py","--port", "10666"]
    networks:
      - back_net

  gaiamaps:
    image: gastudil/gaiamaps:02.00-production-latest
    platform: linux/amd64 
    hostname: gaiamaps
    container_name: gaiamaps
    networks:
      - back_net
      
networks:
  back_net:
